01OA/lshOA.UI/Controllers/WF_InstanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lshOA.UI.Controllers
{
    public class WF_InstanceController : BaseController
    {
        IBLL.IWF_TempBLL wf_TempBLL { get; set; }
        IBLL.IUserInfoBLL userInfoBLL { get; set; }
        // GET: WF_Instance

            /// <summary>
            /// 获取模板列表
            /// </summary>
            /// <returns></returns>
        public ActionResult Index()
        {
            short DelFlag = (short)lshOA.MODEL.Enum.DelFlagEnum.Normarl;
            ViewData.Model = wf_TempBLL.GetList(c => c.DelFlag == DelFlag).ToList();
            return View();
        }

        /// <summary>
        /// 创建流程实例
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult StartWorkflow(int id)
        {
            //获取当前id对应的模板
            var currentTemp = wf_TempBLL.GetList(w => w.ID == id).FirstOrDefault();
            //
            ViewBag.Temp = currentTemp;
            var userInfoList = from u in userInfoBLL.GetList(u => u.DelFlag == 0).ToList()
                               select new SelectListItem()
                               {
                                   Selected = false,
                                   Text = u.UName,
                                   Value = u.ID.ToString()
                               };
            ViewData["FlowTo"] = userInfoList;//如果ViewData中的名字与DropDownList名字一致会自动填充
            return View();
        }
    }
}

01OA/lshOA.UI/Views/WF_Instance/Index.cshtml
@model IEnumerable<lshOA.MODEL.WF_Temp>

@{
   ViewBag.Title = "Index";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TempName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModfiedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DelFlag)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Remark)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TempDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TempForm)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TempStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubBy)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TempName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModfiedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DelFlag)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Remark)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TempDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TempForm)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TempStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubBy)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
               @Html.ActionLink("查看", "StartWorkflow", new { id = item.ID })|
                @Html.ActionLink("跳转至本控制器","StartWorkflow","WF_Instance",new { id=item.ID},null)
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

01OA/lshOA.UI/Views/WF_Instance/StartWorkflow.cshtml
@model lshOA.MODEL.WF_Instance

@{
    Layout = null;
}
@using lshOA.MODEL
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StartWorkflow</title>
    <script src="../../Content/KinderEditor/kindeditor-min.js"></script>
    <link rel="stylesheet" href="../../Content/KinderEditor/themes/default/default.css" />
    <link rel="stylesheet" href="../../Content/KinderEditor/plugins/code/prettify.css" />
    <script charset="utf-8" src="../../Content/KinderEditor/kindeditor.js"></script>
    <script charset="utf-8" src="../../Content/KinderEditor/lang/zh_CN.js"></script>
    <script charset="utf-8" src="../../Content/KinderEditor/plugins/code/prettify.js"></script>
    <script>
//注意编辑器的使用
        KindEditor.ready(function (K) {
            var editor1 = K.create('#TempDescription', {
                cssPath: '../../Content/KinderEditor/plugins/code/prettify.css',
                uploadJson: '../../Content/KinderEditor/asp.net/upload_json.ashx',
                fileManagerJson:

'../../Content/KinderEditor/asp.net/file_manager_json.ashx',
                allowFileManager: true,
                afterCreate: function () {
                    var self = this;
                    //self.sync();//把富文本编辑器的内容放到  文本域里面去。
                }
            });
            var editor2 = K.create('#TempForm', {
                cssPath: '../../Content/KinderEditor/plugins/code/prettify.css',
                uploadJson: '../../Content/KinderEditor/asp.net/upload_json.ashx',
                fileManagerJson:

'../../Content/KinderEditor/asp.net/file_manager_json.ashx',
                allowFileManager: true,
                afterCreate: function () {
                    var self = this;
                    //self.sync();//把富文本编辑器的内容放到  文本域里面去。
                }
            });

            prettyPrint();
        });
    </script>
</head>
<body>
    @using (Html.BeginForm())
    {
        lshOA.MODEL.WF_Temp currentTemp = (WF_Temp)ViewBag.Temp;
        <input type="hidden"name="id" value="@currentTemp" />
        <span>发起 @currentTemp.TempName 流程</span>
        <table>
            <tr>
                <td>流程标题</td>
                <td><input type="text" name="Instance"/></td>
            </tr>
            <tr>
                <td>紧急程度</td>
                <td>
                    <select name="Level">
                        <option value="0">一般</option>
                        <option value="1">紧急</option>
                        <option value="2">速办</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>申请内容</td>
                <td>
                    <textarea id="TempDescription" cols="100" rows="8" style="width:700px;height:200px;visibility:hidden;" name="TempForm">
                        @currentTemp.TempForm
                    </textarea>
                </td>
            </tr>
            <tr>
                <td>流转到</td>
                <td>@Html.DropDownList("FlowTo")</td>
            </tr>
        </table>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>