HM13OA/Backup/HM13OA.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HM13OA.IService;
using HM13OA.Model;
using HM13OA.UI.Models;

namespace HM13OA.UI.Controllers
{
    public class HomeController :MyBaseController// Controller
    {


        public ActionResult Index()
        {
            //ViewData.Model = ActionInfoService
            //   .GetList(a => (a.IsDelete == false) && (a.IsMenu == true))
            //   .Select(a => new MenuViewModel()
            //   {
            //       ActionTitle = a.ActionTitle,
            //       ActionName = a.ActionName,
            //       ControllerName = a.ControllerName,
            //       MenuIcon = a.MenuIcon
            //   }).ToList();

            #region 主菜单过滤
            //1准备目标集合
            List<MenuViewModel> listMenu= new List<MenuViewModel>();
            //1.1获取所有的桌面菜单
            List<ActionInfo> list = ActionInfoService.GetList(a => a.IsDelete == false && a.IsMenu == true).ToList();
            //1.2获取当前登录的用户的对象
            UserInfo userInfo = UserInfoService.GetById(UserLogin.UserId);
            //1.3遍历所有桌面菜单，逐个判断是否有权限
            foreach (var actionInfo in list)
            {

                //根据当前数据，构造一个菜单对象
                MenuViewModel menu = new MenuViewModel()
                {
                    ActionTitle = actionInfo.ActionTitle,
                    ControllerName = actionInfo.ControllerName,
                    ActionName = actionInfo.ActionName,
                    MenuIcon = actionInfo.MenuIcon
                };

                //如果当前用户是admin，则不需要判断直接进入
                if (UserLogin.UserName.Equals("admin"))
                {
                    listMenu.Add(menu);
                    continue;
                }


                //2、查找否决中是否允许，如果允许，直接加入目标集合
                if (UserActionService.GetList(ua =>
                    (ua.ActionId == actionInfo.ActionId) &&
                    (ua.UserId == UserLogin.UserId) &&
                    (ua.IsAllow == true)).Count() > 0)
                {
                    listMenu.Add(menu);
                    continue;
                }

                //3、如果特权没有允许，则查找角色-权限过程
                var result1 = from r in userInfo.RoleInfo//from a in list<a>
                    from a in r.ActionInfo
                    where a.ActionId == actionInfo.ActionId
                    select a;
                if (result1.Count() > 0)
                {
                    listMenu.Add(menu);
                }

                //4、排除拒绝的特殊权限
                var result2 = from ua in userInfo.UserAction
                    where ua.ActionId == actionInfo.ActionId 
                    && 
                    ua.IsAllow == false
                    select ua;
                if (result2.Count() > 0)
                {
                    listMenu.Remove(menu);
                }
            }
            #endregion

            return View(listMenu);
        }

    }
}

HM13OA/Backup/HM13OA.UI/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNetOpenAuth.OpenId.Extensions.AttributeExchange;
using HM13OA.Common;
using HM13OA.IService;
using HM13OA.Model;
using HM13OA.UI.Models;

namespace HM13OA.UI.Controllers
{
    public class UserLoginController : Controller
    {
        public IUserInfoService UserInfoService { get; set; }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ValidateCode()
        {
            ValidateCode vCode = new ValidateCode();
            string code = vCode.CreateValidateCode(4);
            Session["ValidateCode"] = code;
            byte[] bytes = vCode.CreateValidateGraphic(code);
            return File(bytes, @"image/jpeg");

        }
        [HttpPost]
        public ActionResult Login(UserInfoViewModel userInfo)
        {
            string result = "no";


            //判断是否是一个正常的请求
            if (Session["ValidateCode"] == null || Session["ValidateCode"].ToString() == "")
            {
                return Content("请正常请求");
            }

            string vcode = Request["vCode"];
            //先匹配验证码
            if (Session["ValidateCode"].ToString().Equals(vcode,StringComparison.InvariantCultureIgnoreCase))
            {
                int id1;
                //根据用户名密码进行查询
                if (UserInfoService.Login(new UserInfo()
                {
                    UserName = userInfo.UserName,
                    UserPwd = userInfo.UserPwd
                },out id1))
                {
                    result = "ok";
                    userInfo.UserId = id1;

                    //去session，改成分布式缓存
                    //Session["UserLogin"] = userInfo;

                    //使用分布式缓存进行登录操作
                    //1、创建标识
                    string key = Guid.NewGuid().ToString();
                    //2、向客户端写标识
                   Response.Cookies.Add(new HttpCookie("loginId",key));
                    //3、向分布式缓存服务器写信息
                    MmHelper helper=new MmHelper();
                    helper.Set(key, userInfo, DateTime.Now.AddMinutes(20));
                }
                else
                {
                    result = "用户名或密码错误";
                    Session["ValidateCode"] = "";
                }
            }
            else
            {
                //验证码不匹配
                result = "验证码错误";
                Session["ValidateCode"] = "";
            }

            return Content(result);
        }

        public ActionResult Logout()
        {
            //去session
            //Session["UserInfo"] = null;

            //使用分布式缓存的用户注销
            if (Request.Cookies.Get("loginId") != null)
            {
                string key = Request.Cookies.Get("loginId").Value;
                //1、更新客户端cookie
                //Response.Cookies["loginId"].Expires = DateTime.Now.AddMinutes(-1);
                //2、销毁分布式缓存中的对象
                MmHelper helper=new MmHelper();
                helper.Delete(key);
            }

            return RedirectToAction("Index");
        }
    }
}

HM13OA/Backup/HM13OA.UI/Views/Home/Index.cshtml
@model List<HM13OA.UI.Models.MenuViewModel>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/easyUI/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/easyUI/icon.css" rel="stylesheet" />
    <link href="~/Content/ligureUI/Aqua/css/ligerui-all.css" rel="stylesheet" />
    <link href="~/Content/ligureUI/ligerui-icons.css" rel="stylesheet" />


    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/ligerui.min.js"></script>
    <title>Index</title>

    <style>
        .north {
            height:79px;
            background: url(/Content/Images/bg3.png);
            padding-top: 10px; 
        }
        #logo,.north h1 {
            float: left;
        }
        #logout {
            float: right;
        }

                .l-case-title
        {
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 20px;
        }
        body, html
        {
            width: 100%;
            height: 100%;
        }
        *
        {
            margin: 0;
            padding: 0;
        }
        #winlinks
        {
            position: absolute;
            left: 20px;
            top: 20px;
            width: 100%;
        }
        #winlinks ul
        {
            position: relative;
        }
        #winlinks li
        {
            width: 70px;
            cursor: pointer;
            height: 80px;
            position: absolute;
            z-index: 101;
            list-style: none;
            text-align: center;
        }
        #winlinks li img
        {
            width: 36px;
            height: 36px;
        }
        #winlinks li span
        {
            background: none repeat scroll 0 0 rgba(0, 0, 0, 0.3);
            border-radius: 10px 10px 10px 10px;
            display: block;
            font-size: 12px;
            margin-top: 1px;
            color: White;
            line-height: 18px;
            text-align: center;
        }
        #winlinks li.l-over div.bg
        {
            display: block;
        }
        #winlinks li div.bg
        {
            display: none;
            position: absolute;
            top: -2px;
            left: -2px;
            z-index: 0;
            width: 75px;
            height: 64px;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            background: #000;
            opacity: 0.1;
            filter: alpha(opacity=10);
        }
        .l-taskbar-task-icon
        {
            top: 3px; left: 6px; background-image:none;
        } 
        .l-taskbar-task-content{ margin-left:30px;}
        .l-taskbar-task-icon img
        {
            width: 22px;
            height: 22px;
        }
    </style>
</head>
<body class="easyui-layout">
    <div data-options="region:'north',border:false" class="north">
        <img src="~/Content/Images/logo.gif" id="logo" />
        <h1>黑马13协同OA管理系统</h1>
        <a href="@Url.Action("Logout","UserLogin")"><img src="~/Content/Images/big.png" id="logout" border="0" /></a>
    </div>
    <div data-options="region:'center'" style="overflow: hidden; background: url(/Content/Images/win8.jpg) no-repeat  center center;">
        <div id="winlinks">
            <ul>
            </ul>
        </div>
    </div>
</body>
</html>
<script type="text/javascript">
    var LINKWIDTH = 90, LINKHEIGHT = 90, TASKBARHEIGHT = 43;
    var winlinksul =  $("#winlinks ul");
    function f_open(url, title, icon) {
        var win = $.ligerDialog.open(
        { height: 500, url: url, width: 600, showMax: true, showToggle: true, showMin: true, isResize: true, modal: false, title: title, slide: false, buttons: [
            { text: '确定', onclick: function (item, Dialog, index) {
                win.hide();
            }
            }
        ]
        });
        var task = jQuery.ligerui.win.tasks[win.id];
        if (task) {
            $(".l-taskbar-task-icon:first", task).html('<img src="' + icon + '" />');
        }
        return win;
    }
    var links = [
        @foreach (var item1 in Model)
            {
  @Html.Raw("{ icon: '"+item1.MenuIcon+"', title: '"+item1.ActionTitle+"', url: '"+Url.Action(item1.ActionName,item1.ControllerName)+"' },")
            }
            //{ icon: '/uploads/3DSMAX.png', title: '填写周报', url: '../case/week.htm' }

        ];
             
    function onResize() {
        var linksHeight = $(window).height() - TASKBARHEIGHT;
        var winlinks = $("#winlinks");
        winlinks.height(linksHeight);
        var colMaxNumber = parseInt(linksHeight / LINKHEIGHT);//一列最多显示几个快捷方式
        for (var i = 0, l = links.length; i < l; i++) {
            var link = links[i];
            var jlink = $("li[linkindex=" + i + "]", winlinks);
            var top = (i % colMaxNumber) * LINKHEIGHT, left = parseInt(i / colMaxNumber) * LINKWIDTH;
            if (isNaN(top) || isNaN(left)) continue;
            jlink.css({ top: top, left: left });
        }

    }
    function linksInit() {
        for (var i = 0, l = links.length; i < l; i++) {
            var link = links[i];
            var jlink;
            var jlink = $("<li></li>");
            jlink.attr("linkindex", i);
            jlink.append("<img src='" + link.icon + "' />");
            jlink.append("<span>" + link.title + "</span>");
            jlink.append("<div class='bg'></div>");
            jlink.hover(function () {
                $(this).addClass("l-over");
            }, function () {
                $(this).removeClass("l-over");
            }).click(function () {
                var linkindex = $(this).attr("linkindex");
                var link = links[linkindex];
                f_open(link.url, link.title, link.icon);
            });
            jlink.appendTo(winlinksul);
        }

    }

    $(window).resize(onResize);
    $.ligerui.win.removeTaskbar = function () { }; //不允许移除
    $.ligerui.win.createTaskbar(); //页面加载时创建任务栏

    linksInit();
    onResize();

</script>