HM13OA/Backup/HM13OA.UI/Controllers/RoleInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Web;
using System.Web.Mvc;
using HM13OA.IService;
using HM13OA.Model;
using Spring.Util;

namespace HM13OA.UI.Controllers
{
    public class RoleInfoController : MyBaseController//Controller
    {
        public IRoleInfoService RoleInfoService { get; set; }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPageList(int page,int rows)
        {
            int total;

            var result = RoleInfoService.GetPageList<int>(
                r => r.IsDelete == false,
                r => r.RoleId,
                rows, page, out total
                ).Select(r=>new
                {
                    r.RoleId,
                    r.RoleName
                });

            return Json(new {total, rows = result});
        }

        public ActionResult Add(RoleInfo roleInfo)
        {
            string result = "no";

            //完善数据
            roleInfo.IsDelete = false;
            if (roleInfo.Remark == null)
            {
                roleInfo.Remark = "";
            }
            roleInfo.SubBy = 1;
            roleInfo.SubTime = DateTime.Now;

            //调用Service方法完成添加
            if (RoleInfoService.Add(roleInfo))
            {
                result = "ok";
            }

            return Content(result);
        }

        public ActionResult Edit(int id1)
        {
            ViewData.Model = RoleInfoService.GetById(id1);
            return View();
        }
        [HttpPost]
        public ActionResult Edit(RoleInfo roleInfo)
        {
            string result = "no";

            roleInfo.IsDelete = false;
            roleInfo.SubBy = 1;
            roleInfo.SubTime = DateTime.Now;
            if (roleInfo.Remark == null)
            {
                roleInfo.Remark = "";
            }

            if (RoleInfoService.Edit(roleInfo))
            {
                result = "ok";
            }

            return Content(result);
        }

        public ActionResult Remove(string idList)
        {
            string result = "no";

            List<int> ids=new List<int>();
            string[] ids2 = idList.Split(',');
            foreach (var id in ids2)
            {
                ids.Add(int.Parse(id));
            }
            if (RoleInfoService.Remove(ids.ToArray()))
            {
                result = "ok";
            }

            return Content(result);
        }

        public ActionResult SetAction(int id1)
        {
            ViewBag.RoleInfo = RoleInfoService.GetById(id1);
            ViewData.Model = ActionInfoService.GetList(a => a.IsDelete == false).ToList();

            return View();
        }
        [HttpPost]
        public ActionResult SetAction(int rid, string aids)
        {
            string result = "no";

            if (RoleInfoService.SetAction(rid, aids))
            {
                result = "ok";
            }

            return Content(result);
        }

    }
}

HM13OA/Backup/HM13OA.UI/Views/RoleInfo/Edit.cshtml
@model HM13OA.Model.RoleInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script>
        function EditAfter(msg) {
            window.parent.EditAfter(msg);
        }

        function EditSubmit() {
            $("form").submit();
        }
    </script>

</head>
<body>
    <div>
        @using (Ajax.BeginForm("Edit", "RoleInfo", new AjaxOptions()
        {
            OnSuccess = "EditAfter"
        }))
        {
            <table border="1">
                <tr>
                    <td>编号：</td>
                    <td>
                        @Model.RoleId
                        <input type="hidden" name="RoleId" value="@Model.RoleId"/>
                    </td>
                </tr>
                <tr>
                    <td>名称：</td>
                    <td>@Html.TextBoxFor(r=>r.RoleName)</td>
                </tr>
                <tr>
                    <td>备注：</td>
                    <td>@Html.TextAreaFor(r=>r.Remark)</td>
                </tr>
            </table>
        }
    </div>
</body>
</html>

HM13OA/Backup/HM13OA.UI/Views/RoleInfo/Index.cshtml
@model HM13OA.Model.RoleInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/easyUI/icon.css" rel="stylesheet" />
    <link href="~/Content/easyUI/default/easyui.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script>
        $(function() {
            $('#addDiv').hide();
            $('#editDiv').hide();
            $('#setActionDiv').hide();


            LoadData();
        });

        function LoadData() {
            $('#roleList').datagrid({
                url: '@Url.Action("GetPageList","RoleInfo")',
                title: '角色列表',
                width: 700,
                height: 400,
                fitColumns: true,
                idField: 'RoleId',
                loadMsg: '正在加载角色的信息...',
                pagination: true,
                singleSelect: false,
                pageSize: 10,
                pageNumber: 1,
                pageList: [10, 20, 30],
                queryParams: {},
                columns: [[
						{ field: 'ck', checkbox: true, align: 'left', width: 50 },
						{ field: 'RoleId', title: '主键', width: 80 },
						{ field: 'RoleName', title: '角色名称', width: 120 }
                ]],
                toolbar: [{
                    id: 'toolbarAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: AddShow
                }, {
                    id: 'toolbarEdit',
                    text: '修改',
                    iconCls: 'icon-edit',
                    handler: EditShow
                }, {
                    id: 'toolbarRemove',
                    text: '删除',
                    iconCls: 'icon-remove',
                    handler: RemoveShow
                }, {
                    id: 'toolbarSetAction',
                    text: '设置权限',
                    iconCls: 'icon-cut',
                    handler: SetActionShow
                }]
            });
        }

        function AddShow() {
            $('#addDiv').show();
            
            $("#addDiv").dialog({
                title: "添加角色",
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,

                buttons: [{
                    text: "添加",
                    iconCls: "icon-add",
                    handler: function () {
                        $("#addDiv form").submit();
                    }
                }, {
                    text: "取消",
                    iconCls: "icon-cancel",
                    handler: function () {
                        $("#addDiv").dialog("close");
                    }
                }]
            });
        }

        function AddAfter(msg) {
            if (msg == "ok") {
                $('#addDiv').dialog("close");

                $('#roleList').datagrid("load");
            } else {
                $.messager.alert('提示','添加失败，请稍候重试');
            }
        }

        function EditShow() {
            //获取选中的项
            var items = $('#roleList').datagrid('getSelections');
            if (items.length != 1) {
                $.messager.alert('警告', '请选中一项后再操作');

                return;
            }

            var id1 = items[0]["RoleId"];
            
            //显示层并修改请求页面
            $('#editDiv iframe').attr('src', '@Url.Action("Edit","RoleInfo")?id1=' + id1);
            $('#editDiv').show();

            $('#editDiv').dialog({
                title: "修改角色",
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,

                buttons: [{
                    text: "修改",
                    iconCls: "icon-edit",
                    handler: function () {
                        $('#editDiv iframe')[0].contentWindow.EditSubmit();
                    }
                }, {
                    text: "取消",
                    iconCls: "icon-cancel",
                    handler: function () {
                        $("#editDiv").dialog("close");
                    }
                }]
            });
        }

        function EditAfter(msg) {
            if (msg == "ok") {
                $('#editDiv').dialog("close");

                $('#roleList').datagrid("reload");
            }
        }

        function RemoveShow() {
            //获取所有选中的项
            var items = $('#roleList').datagrid('getSelections');
            if (items.length <= 0) {
                $.messager.alert('警告', '渣渣，你要哪样');
                return;
            }

            $.messager.confirm('提示', '确定要删除吗？', function(msg) {
                if (msg) {
                    //整理编号
                    var ids = '';
                    $.each(items, function(i, item) {
                        ids += item["RoleId"] + ',';
                    });
                    ids = ids.substring(0, ids.length - 1);
                    
                    //向服务器发请求
                    $.post('@Url.Action("Remove","RoleInfo")',
                        {
                            idList: ids
                        }, function(msg) {
                            if (msg == "ok") {
                                $('#roleList').datagrid('reload');
                            } else {
                                $.messager.alert('提示','删除失败，请稍候重试');
                            }
                        });
                }
            });
        }

        function SetActionShow() {
            var items = $('#roleList').datagrid('getSelections');
            if (items.length != 1) {
                $.messager.alert('提示', '请选择一项后再分配角色');
                return;
            }

            var id1 = items[0]["RoleId"];

            $('#setActionDiv iframe').attr('src', '@Url.Action("SetAction","RoleInfo")?id1=' + id1);
            $('#setActionDiv').show();
            $('#setActionDiv').dialog({
                title: "为角色分配权限",
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,
                width: 400,
                height:500,

                buttons: [{
                    text: "设置",
                    iconCls: "icon-cut",
                    handler: function () {
                        $('#setActionDiv iframe')[0].contentWindow.SetActionDeal();
                    }
                }, {
                    text: "取消",
                    iconCls: "icon-cancel",
                    handler: function () {
                        $("#setActionDiv").dialog("close");
                    }
                }]
            });
        }
        
        function SetActionAfter(msg) {
            if (msg == "ok") {
                $('#setActionDiv').dialog('close');
                $('#roleList').datagrid('clearSelections');
            } else {
                $.messager.alert('提示', '设置角色失败，请稍候重试');
            }
        }
    </script>
</head>
<body>
   <!--角色列表-->
    <div>
        <table id="roleList"></table>
    </div>
    
    <!--角色添加-->
    <div id="addDiv">
        @using (Ajax.BeginForm("Add", "RoleInfo", new AjaxOptions()
        {
            OnSuccess = "AddAfter"
        }))
        {
            <table border="1">
                <tr>
                    <td>角色名称：</td>
                    <td>@Html.TextBoxFor(r=>r.RoleName)</td>
                </tr>
                <tr>
                    <td>备注：</td>
                    <td>@Html.TextAreaFor(r=>r.Remark)</td>
                </tr>
            </table>
        }
    </div>
    
    <!--角色修改-->
    <div id="editDiv">
        <iframe src="/Error.html" frameborder="0" width="100%" height="100%"></iframe>
    </div>
    
            <!--分配权限-->
        <div id="setActionDiv">
            <iframe src="/Error.html" frameborder="0" width="100%" height="100%"></iframe>
        </div>

</body>
</html>

HM13OA/Backup/HM13OA.UI/Views/RoleInfo/SetAction.cshtml
@using HM13OA.Model
@model List<HM13OA.Model.ActionInfo>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetAction</title>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script>
        function SetActionDeal() {
            //获取所有选中的项
            var ids = '';
            $(':checked').each(function() {
                ids += $(this).val() + ',';
            });
            if (ids == '') {
                alert('请选择权限后再设置');
                return;
            }
            ids = ids.substring(0, ids.length - 1);

            var rid1 = $('#RoleId').val();
            
            //向服务器端发请求
            $.post('@Url.Action("SetAction","RoleInfo")', {
                    rid: rid1,
                    aids: ids
                }, function(msg) {
                    window.parent.SetActionAfter(msg);
                });
        }
    </script>
</head>
<body>
    <div>
        @{
            var roleInfo = ViewBag.RoleInfo as RoleInfo;
           <input  type="hidden" name="RoleId" id="RoleId" value="@roleInfo.RoleId"/><br/>
            int counter = Model.Count;
            for (int i = 0; i < counter; i++)
            {
                <input type="checkbox" value="@Model[i].ActionId"
                    
                    @if (roleInfo.ActionInfo.Contains(Model[i]))
                    {
                        @Html.Raw("checked='checked'")
                    }
                    
                    />@Model[i].ActionTitle
                if ((i+1)%4 == 0)
                {
                    <br/>
                }
            }
        }    </div>
</body>
</html>